export type SpEvent = {
  id: number;
  last_update: string;
  date: Date;
  description: string;
  price: string;
  town: string;
  town_latitude: number;
  town_longitude: number;
  department: number | null;
  place: string;
  place_address: string;
  place_latitude: number;
  place_longitude: number;
  country_code: string;
  country_name: string;
  category: number;
  sub_category: string;
  is_covered_place: boolean;
  has_car_park: boolean;
  has_parquet_floor: boolean;
};
